[package]
name = "netrun"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
nix = { version = "0.29", features = ["sched", "signal", "process", "fs", "net", "user"] }
anyhow = "1"
rtnetlink = "0.14"
tokio = { version = "1", features = ["rt", "sync", "fs", "macros"] }
futures = "0.3"
ctrlc = "3"
ipnet = "2"
